name: Daily BTC Prediction

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  run-prediction:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install openai requests

      - name: Download latest log (if any)
        run: |
          mkdir -p log
          echo "placeholder" > log/dummy.txt
          gh run list --limit 1 --json databaseId --jq '.[0].databaseId' > run_id.txt
          RUN_ID=$(cat run_id.txt)
          gh run download $RUN_ID -n btc-log --dir log || echo "No previous log found"
          mv log/btc_predictions_log.csv btc_predictions_log.csv || echo "Starting new log"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run prediction script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        run: python openai_predict.py

      - name: Upload prediction logs
        uses: actions/upload-artifact@v4
        with:
          name: predictions-${{ github.run_number }}
          path: |
            btc_predictions_log.csv
            gold_predictions_log.csv
          if-no-files-found: warn
    
      - name: Commit and push updated log
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
          git add btc_predictions_log.csv
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update BTC prediction log [auto]"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
